sudo: false
language: java
jdk:
- openjdk8
script:
- test/run.sh
notifications:
  slack:
    secure: MvGcupncujpGgQ9L//QrQq5LAOVP3FYna4GnJ8SALQk6tWO8hvjpEDcXJsS3pK9aY3C6T/zOpZdrw/4UqO3GMlyJI//mLlHyCqGC8+gWFB9AHDNFEXLkqhzSgptJ8P039A3/Z4MI6/2G0jZkDfThjjqRdkRxmRJqndfqX9oHIgw=
